services:
  db:
    image: postgres:15-alpine
    container_name: social_platform_db
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_platform_backend
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social_platform_frontend
    restart: unless-stopped
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: social_platform_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: unless-stopped
    command: celery -A src.core.celery_app worker --loglevel=info
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    depends_on:
      - backend
      - redis
      - db
  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_beat
    restart: unless-stopped
    command: celery -A src.core.celery_app beat --loglevel=info
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - backend
      - redis
volumes:
  postgres_data:
  redis_data:
  uploads: