version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: social_platform_db
    restart: unless-stopped
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_platform_backend
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: social_platform_frontend
  #   restart: unless-stopped
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - backend

volumes:
  postgres_data:
  backend:
  
